### ISSUE TITLE
Is maven repository exist for 'org.unbroken-dome.vertx-spring:vertx-spring?

### ISSUE THREAD

**Issue by armdev** [unbroken-dome/vertx-spring#1]
Is maven repository exist for 'org.unbroken-dome.vertx-spring:vertx-spring?

**Comment by tkrullmann** [comment]
Hi,

the artifacts are hosted on [JCenter](https://bintray.com/bintray/jcenter).

(The "Set me up" button shows instructions for setting up the repository for various build tools.)

I believe the Maven repository URL is https://jcenter.bintray.com

**Comment by armdev** [comment]
Hi,
Many thanks.
